CREATE TABLE Grad (
    ID_GR INTEGER PRIMARY KEY,
    NAZ_GR VARCHAR2(50) NOT NULL,
    POS_BR VARCHAR2(10),
    BR_ST INTEGER
);

CREATE TABLE StudentskiDom (
    ID_STD INTEGER PRIMARY KEY,
    NAZ_STD VARCHAR2(50) NOT NULL,
    ADR VARCHAR2(100),
    KAPAC INTEGER,
    ID_GR INTEGER NOT NULL,
    FOREIGN KEY (ID_GR) REFERENCES Grad(ID_GR)
);

CREATE TABLE Soba (
    ID_SOB INTEGER PRIMARY KEY,
    BR_KREV INTEGER,
    SPRAT INTEGER,
    ID_STD INTEGER NOT NULL,
    FOREIGN KEY (ID_STD) REFERENCES StudentskiDom(ID_STD)
);

CREATE TABLE Inventar (
    ID_INV INTEGER PRIMARY KEY,
    KOLICINA INTEGER,
    NAZ_INV VARCHAR2(50),
    VRED_INV NUMBER(10, 2),
    STANJE VARCHAR2(20),
    ID_SOB INTEGER NOT NULL,
    FOREIGN KEY (ID_SOB) REFERENCES Soba(ID_SOB)
);

CREATE TABLE Student (
    ID_STUD INTEGER PRIMARY KEY,
    IME_STUD VARCHAR2(50),
    PRZ_STUD VARCHAR2(50),
    POL_STUD CHAR(1),
    TEL_STUD VARCHAR2(20),
    ADR_STUD VARCHAR2(100),
    ID_SOB INTEGER NOT NULL,
    FOREIGN KEY (ID_SOB) REFERENCES Soba(ID_SOB)
);

CREATE TABLE Fakultet (
    ID_FAK INTEGER PRIMARY KEY,
    NAZ_FAK VARCHAR2(100),
    ADR_FAK VARCHAR2(100),
    TEL_FAK VARCHAR2(20),
    WEB VARCHAR2(100)
);

CREATE TABLE Studira (
    ID_STUD INTEGER NOT NULL,
    ID_FAK INTEGER NOT NULL,
    PRIMARY KEY (ID_STUD, ID_FAK),
    FOREIGN KEY (ID_STUD) REFERENCES Student(ID_STUD),
    FOREIGN KEY (ID_FAK) REFERENCES Fakultet(ID_FAK)
);

CREATE TABLE Placanje (
    ID_PLAC INTEGER PRIMARY KEY,
    UK_IZNOS NUMBER(10, 2),
    TIP_PL VARCHAR2(50),
    DAT_PLAC DATE,
    OPIS_PL VARCHAR2(200),
    ID_STUD INTEGER NOT NULL,
    FOREIGN KEY (ID_STUD) REFERENCES Student(ID_STUD)
);

CREATE TABLE Zaposleni (
    ID_ZAP INTEGER PRIMARY KEY,
    IME_ZAP VARCHAR2(50),
    PRZ_ZAP VARCHAR2(50),
    DAT_RODJ DATE,
    BRTEL VARCHAR2(20),
    TIP_ZAP VARCHAR2(20),
    ID_STD INTEGER NOT NULL,
    FOREIGN KEY (ID_STD) REFERENCES StudentskiDom(ID_STD)
);

CREATE TABLE Domar (
    ID_ZAP INTEGER PRIMARY KEY,
    FOREIGN KEY (ID_ZAP) REFERENCES Zaposleni(ID_ZAP)
);

CREATE TABLE Kvar (
    ID_KV INTEGER PRIMARY KEY,
    STAT_KV VARCHAR2(20),
    OPIS_KV VARCHAR2(200),
    PRIORITET VARCHAR2(20),
    ID_STUD NUMBER(38) NOT NULL,
    ID_ZAP NUMBER(38) NOT NULL,
    FOREIGN KEY (ID_STUD) REFERENCES STUDENT(ID_STUD),
    FOREIGN KEY (ID_ZAP) REFERENCES DOMAR(ID_ZAP)
);

CREATE TABLE Upravnik (
    ID_ZAP INTEGER PRIMARY KEY,
    FOREIGN KEY (ID_ZAP) REFERENCES Zaposleni(ID_ZAP)
);

CREATE TABLE Kartica (
    ID_KART INTEGER PRIMARY KEY,
    DAT_OD DATE,
    DAT_DO DATE,
    TIP_KART VARCHAR2(20),
    ID_ZAP INTEGER NOT NULL,
    ID_STUD INTEGER NOT NULL,
    FOREIGN KEY (ID_ZAP) REFERENCES Upravnik(ID_ZAP),
    FOREIGN KEY (ID_STUD) REFERENCES Student(ID_STUD)
);

CREATE TABLE Cistacica (
    ID_ZAP INTEGER PRIMARY KEY,
    ID_NADR INTEGER,
    FOREIGN KEY (ID_ZAP) REFERENCES Zaposleni(ID_ZAP),
    FOREIGN KEY (ID_NADR) REFERENCES Cistacica(ID_ZAP)
);

CREATE TABLE CISCENJE (
    ID_ZAP INTEGER NOT NULL,
    DAT_CISC DATE NOT NULL,
    ID_SOB   INTEGER NOT NULL,
    PRIMARY KEY (ID_ZAP, DAT_CISC),
    FOREIGN KEY (ID_ZAP) REFERENCES CISTACICA(ID_ZAP),
    FOREIGN KEY (ID_SOB) REFERENCES SOBA(ID_SOB)
);